### PR TITLE
Support Django 1.7 and Python 3

### PR DESCRIPTION
**Pull request by SunilMohanAdapa**
- Add python3 testing to makefile.

- Advertise python 3 and 3.4 in classifiers.

- Advertise Django 1.7 support in README.

- Rename test modules to start with 'test' for better consistency with unittest
  module and new Django test runner.

- Explictly set TEST_RUNNER in test_project settings to avoid Django from
  throwing a warning.

- Fix test_project/urls.py to work with absense of relative imports in python3.

### CODE REVIEW

**Comment by mgrouchy** [comment]
hi @SunilMohanAdapa This looks great. Will rerun the tests(think there is just a timeout issue, that broke one of the test runs) Then I will get it merged and package up a release. Thanks!

**Comment by SunilMohanAdapa** [comment]
Thank you for quick response, merge and release.  I can now get started with packaging for Debian.

**Comment by mgrouchy** [comment]
Awesome, if you need anything else to make that happen let me know.

**Comment by abrahammartin** [comment]
Hello,

a colleague of mine did package the version 0.2.6 of django-stronghold for Debian. You can find it here: https://git.csx.cam.ac.uk/x/ucs/u/mcv21/django-stronghold.git

He wanted to upload it to the oficial debian repo, thus it can be maintained and updated by the python debian community. You can see the thread in debian mailing list here: https://lists.debian.org/debian-python/2014/08/msg00024.html

The debian team agreed to open an oficial git repo for the package in the debian git repo [http://anonscm.debian.org/cgit/collab-maint/django-stronghold.git/] but my colleague failed to upload it because he became busy with other things.

It may be of your interest to continue where he left and get the package inside the oficial debian repo. 

Thanks for the work!

**Comment by SunilMohanAdapa** [comment]
On Tuesday 17 February 2015 09:50 PM, Abraham Martin wrote:
> Hello,
> 
> a colleague of mine did package the version 0.2.6 of django-stronghold
> for Debian. You can find it here:
> https://git.csx.cam.ac.uk/x/ucs/u/mcv21/django-stronghold.git
> 
> He wanted to upload it to the oficial debian repo, thus it can be
> maintained and updated by the python debian community. You can see the
> thread in debian mailing list here:
> https://lists.debian.org/debian-python/2014/08/msg00024.html

Today, I filed an ITP bug today announcing my intent to package:
https://bugs.debian.org/778602 .  I searched for existing ones but
didn't find any.  I just finished creating the package myself and am
about submit for review.  I could have avoided some effort had I known
earlier. :)

> 
> The debian team agreed to open an oficial git repo for the package in
> the debian git repo
> [http://anonscm.debian.org/cgit/collab-maint/django-stronghold.git/] but
> my colleague failed to upload it because he became busy with other things.

I did create that exact repo there today.  I will be uploading my work
there soon.

> 
> It may be of your interest to continue where he left and get the package
> inside the oficial debian repo.

Thank you for the information.  I will try to check the work done and
see if there is something I can use from it.

-- 
Sunil

**Comment by abrahammartin** [comment]
On 17 February 2015 at 18:10, Sunil Mohan Adapa <notifications@github.com>
wrote:

> On Tuesday 17 February 2015 09:50 PM, Abraham Martin wrote:
> > Hello,
> >
> > a colleague of mine did package the version 0.2.6 of django-stronghold
> > for Debian. You can find it here:
> > https://git.csx.cam.ac.uk/x/ucs/u/mcv21/django-stronghold.git
> >
> > He wanted to upload it to the oficial debian repo, thus it can be
> > maintained and updated by the python debian community. You can see the
> > thread in debian mailing list here:
> > https://lists.debian.org/debian-python/2014/08/msg00024.html
>
> Today, I filed an ITP bug today announcing my intent to package:
> https://bugs.debian.org/778602 . I searched for existing ones but
> didn't find any. I just finished creating the package myself and am
> about submit for review. I could have avoided some effort had I known
> earlier. :)
>

Great :)


>
> >
> > The debian team agreed to open an oficial git repo for the package in
> > the debian git repo
> > [http://anonscm.debian.org/cgit/collab-maint/django-stronghold.git/] but
> > my colleague failed to upload it because he became busy with other
> things.
>
> I did create that exact repo there today. I will be uploading my work
> there soon.
>

Oh! I thought the python debian team created it back in August :)


>
> >
> > It may be of your interest to continue where he left and get the package
> > inside the oficial debian repo.
>
> Thank you for the information. I will try to check the work done and
> see if there is something I can use from it.


:)

**Comment by SunilMohanAdapa** [comment]
Just an update. python-django-stronghold and python3-django-stronghold are now available available in Debian.

**Comment by mgrouchy** [comment]
very cool! Thanks @SunilMohanAdapa !

**Comment by abrahammartin** [comment]
Great news! Thank you @SunilMohanAdapa

**Pull request merged**
