### PR TITLE
Add Django 2.0 support

### PR DESCRIPTION
**Pull request by dvl**

### CODE REVIEW

**Comment by underyx** [comment]
Django 2.x requires Python 3, so you can remove those combinations from the Travis build matrix.

**Comment by dvl** [comment]
All tests passing now

**Comment by underyx** [comment]
I assume this is a nice time to ping @mgrouchy then to have this merged?

**Comment by netman92** [comment]
@mgrouchy is it possible to merge this?

**Comment by mgrouchy** [comment]
Ill take a look at this, this evening and carve up a new release.

**Comment by mgrouchy** [comment]
sorry, merged another PR that caused conflicts here, if you can fix those in .travis.yml I will get this merged.

**Comment by dvl** [comment]
No problem, I'll take a look when I wake up

**Comment by mgrouchy** [comment]
@dvl thanks! :)

**Comment by dvl** [comment]
@mgrouchy I think it's fine now, please tell me if I'm missing something.

**Comment by shacker** [comment]
Nice timing - just had a Django 2 project update blocked by this issue - thanks and looking forward!

**Comment by mgrouchy** [comment]
@dvl I think this looks good! Thanks!

**Comment by shacker** [comment]
Works perfectly, thanks much.

**Pull request merged**
